

package com.selfnv_payment.Model;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * This is the model class for the Item Master
 */
public class ItemModel implements Parcelable {

    // State
    private String itemNumber;
    private String itemDesc;
    private String unitOfMeasure;
    private String itemPrice;

    private String itemName;
    private String itemSoh;
    private String itemFacings;
    private String itemMinimumOrderQuantity;
    private String itemMinimumDisplayQuantity;
    private String date;
    private String reason;
    private String itemTax;
    private String timeStamp;


    public ItemModel() {

    }



    public static Creator<ItemModel> getCREATOR() {
        return CREATOR;
    }

    /**
     * Constructor
     * @param itemNumber    The item number from the barcode but this is not the one generated by Server
     * @param itemDesc      The name and the spec for this item
     * @param unitOfMeasure Unit of measure
     * @param itemPrice     Selling price
     * @param //itemName      the name of the product
     * @param //facings       how many facings on the shelf does it hace
     * @param //minimumOrderQuantity (MOQ) the value of stock quantity that is ordered by MDQ
     * @param //minimumDisplayQuantity (MDG) The minimum stock held before trigger order more event
     */
    public ItemModel(String itemNumber, String itemDesc, String unitOfMeasure, String itemPrice, String itemName, String soh, String facings, String minimumOrderQuantity, String minimumDisplayQuantity, String tax) {

        this.itemNumber = itemNumber;
        this.itemDesc = itemDesc;
        this.unitOfMeasure = unitOfMeasure;
        this.itemPrice = itemPrice;
        this.itemName = itemName;
        this.itemSoh = soh;
        this.itemFacings = facings;
        this.itemMinimumOrderQuantity = minimumOrderQuantity;
        this.itemMinimumDisplayQuantity = minimumDisplayQuantity ;
        this.itemTax = tax;


    }

    public ItemModel(String itemNumber, String date, String reason, String itemSoh, String timeStamp){

        this.itemNumber = itemNumber;
        this.date = date;
        this.reason = reason;
        this.itemSoh = itemSoh;
        this.timeStamp = timeStamp;
    }

    public ItemModel(String itemNumber, String date, String itemSoh, boolean itemModel_date) {

        this.itemNumber = itemNumber;
        this.date = date;
        this.itemSoh = itemSoh;

    }

    public void setItemSoh(String itemSoh) {
        this.itemSoh = itemSoh;
    }

    public String getItemFacings() {
        return itemFacings;
    }

    public void setItemFacings(String itemFacings) {
        this.itemFacings = itemFacings;
    }

    public String getItemMinimumOrderQuantity() {
        return itemMinimumOrderQuantity;
    }

    public void setItemMinimumOrderQuantity(String itemMinimumOrderQuantity) {
        this.itemMinimumOrderQuantity = itemMinimumOrderQuantity;
    }

    public String getItemMinimumDisplayQuantity() {
        return itemMinimumDisplayQuantity;
    }

    public void setItemMinimumDisplayQuantity(String itemMinimumDisplayQuantity) {
        this.itemMinimumDisplayQuantity = itemMinimumDisplayQuantity;
    }

    public String getItemTax() {
        return itemTax;
    }

    public void setItemTax(String itemTax) {
        this.itemTax = itemTax;
    }

    public String getItemNumber() {
        return itemNumber;
    }

    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
    }

    public String getItemDesc() {
        return itemDesc;
    }

    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }

    public String getItemPrice() {
        return itemPrice;
    }

    public String getItemName() {
        return itemName;
    }


    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public void setItemPrice(String itemPrice) {
        this.itemPrice = itemPrice;
    }

    public String getItemSoh() {
        return itemSoh;
    }

    public void setSoh(String itemSoh) {
        this.itemSoh = itemSoh;
    }

    public String getFacings() {
        return itemFacings;
    }

    public void setFacings(String itemFacings) {
        this.itemFacings = itemFacings;
    }

    public String getMinimumOrderQuantity() {
        return itemMinimumOrderQuantity;
    }

    public void setMinimumOrderQuantity(String minimumOrderQuantity) {
        this.itemMinimumOrderQuantity = minimumOrderQuantity;
    }


    public String getMinimumDisplayQuantity() {
        return itemMinimumDisplayQuantity;
    }

    public void setMinimumDisplayQuantity(String itemMinimumDisplayQuantity) {
        this.itemMinimumDisplayQuantity = itemMinimumDisplayQuantity;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    protected ItemModel(Parcel in) {
        itemNumber = in.readString();
        itemDesc = in.readString();
        unitOfMeasure = in.readString();
        itemPrice = in.readString();
        itemName= in.readString();
        itemSoh= in.readString();
        itemFacings= in.readString();
        itemMinimumOrderQuantity= in.readString();
        itemMinimumDisplayQuantity= in.readString();

        date=in.readString();
        reason=in.readString();
        itemTax=in.readString();
        timeStamp = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(itemNumber);
        dest.writeString(itemDesc);
        dest.writeString(unitOfMeasure);
        dest.writeString(itemPrice);

        dest.writeString(itemName);
        dest.writeString(itemSoh);
        dest.writeString(itemFacings);
        dest.writeString(itemMinimumOrderQuantity);
        dest.writeString(itemMinimumDisplayQuantity);

        dest.writeString(date);
        dest.writeString(reason);

        dest.writeString(itemTax);
        dest.writeString(timeStamp);
    }

    @SuppressWarnings("unused")
    public static final Creator<ItemModel> CREATOR = new Creator<ItemModel>() {
        @Override
        public ItemModel createFromParcel(Parcel in) {
            return new ItemModel(in);
        }

        @Override
        public ItemModel[] newArray(int size) {
            return new ItemModel[size];
        }
    };
}
